baseURL = "https://rohannevrikar.github.io/blog/"
languageCode = "en-us"
title = "Rohan's brain dump"
theme = "PaperMod"

[params]
  description = "Daily learnings and notes"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  defaultTheme = "auto"

[params.homeInfoParams]
  Title = "Hi, I'm Rohan"
  Content = "I spend most of my day working with AI. This blog is my space to still feel like a human. Writing here to think out loud and share what I'm learning."

[[menu.main]]
  name = "Archive"
  url = "/archives/"
  weight = 5

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 10
